sudo: required

services:
  - docker

script:
  - docker build -t dlang-tour/dlang-tour-exec:dmd-nightly .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push dlang-tour/dlang-tour-exec:dmd-nightly
